substitutions: !include work_sensors.yaml
  
esphomeyaml:
  name: office_thermostat_five
  platform: ESP8266
  board: esp12e

wifi:
  ssid: $work_ssid
  password: $work_ssid_password
  #manual_ip:
    # Set this to the IP of the ESP
    #static_ip: 192.168.13.132
    # Set this to the IP address of the router. Often ends with .2
    #gateway: $work_gateway
    # The subnet of the network. 255.255.255.0 works for most home networks.
    #subnet: $work_subnet

mqtt:
  broker: $mqtt_broker
  username: $mqtt_username
  password: $mqtt_password

# Enable logging
logger:

ota:

dallas:
  - pin: GPIO2

# Individual sensors
sensor:
- platform: dallas
  address: 0x3002131BFF9FAA28
  name: "Office Thermostat Five"

