esphomeyaml:
  name: office_thermostat_one
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'No Internet Access'
  password: 'MikIsADonkey'
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.13.131
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.13.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  

mqtt:
  broker: '192.168.13.1'
  username: 'SquiggleyMqtt'
  password: 'DangerMqtt42'

# Enable logging
logger:

ota:

dallas:
  - pin: D4

# Individual sensors
sensor:
  - platform: dallas
    address: 0xFA02131B147EAA28
    name: "Office Thermostat One"
